/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessScoreRouteImport } from './routes/wellness-score'
import { Route as SmartCalculatorsRouteImport } from './routes/smart-calculators'
import { Route as BodyAssessmentRouteImport } from './routes/body-assessment'
import { Route as IndexRouteImport } from './routes/index'

const WellnessScoreRoute = WellnessScoreRouteImport.update({
  id: '/wellness-score',
  path: '/wellness-score',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartCalculatorsRoute = SmartCalculatorsRouteImport.update({
  id: '/smart-calculators',
  path: '/smart-calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyAssessmentRoute = BodyAssessmentRouteImport.update({
  id: '/body-assessment',
  path: '/body-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body-assessment': typeof BodyAssessmentRoute
  '/smart-calculators': typeof SmartCalculatorsRoute
  '/wellness-score': typeof WellnessScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body-assessment': typeof BodyAssessmentRoute
  '/smart-calculators': typeof SmartCalculatorsRoute
  '/wellness-score': typeof WellnessScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body-assessment': typeof BodyAssessmentRoute
  '/smart-calculators': typeof SmartCalculatorsRoute
  '/wellness-score': typeof WellnessScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/body-assessment' | '/smart-calculators' | '/wellness-score'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/body-assessment' | '/smart-calculators' | '/wellness-score'
  id:
    | '__root__'
    | '/'
    | '/body-assessment'
    | '/smart-calculators'
    | '/wellness-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyAssessmentRoute: typeof BodyAssessmentRoute
  SmartCalculatorsRoute: typeof SmartCalculatorsRoute
  WellnessScoreRoute: typeof WellnessScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-score': {
      id: '/wellness-score'
      path: '/wellness-score'
      fullPath: '/wellness-score'
      preLoaderRoute: typeof WellnessScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-calculators': {
      id: '/smart-calculators'
      path: '/smart-calculators'
      fullPath: '/smart-calculators'
      preLoaderRoute: typeof SmartCalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-assessment': {
      id: '/body-assessment'
      path: '/body-assessment'
      fullPath: '/body-assessment'
      preLoaderRoute: typeof BodyAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyAssessmentRoute: BodyAssessmentRoute,
  SmartCalculatorsRoute: SmartCalculatorsRoute,
  WellnessScoreRoute: WellnessScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
